[package]
name = "proxying"
version = "0.1.0"
edition = "2024"

[dependencies]
postcard.workspace = true
redis.workspace = true
serde.workspace = true
shared.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
